# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180701_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/cf21e78c399942a3bbf5d6640ebb93e0'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/cf21e78c399942a3bbf5d6640ebb93e0', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='0d72f6b905974867bfb0adce92be7789', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
