# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180701_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/a76f920bea6a4225a007dd73ca63b541'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/a76f920bea6a4225a007dd73ca63b541', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='575803bd4b9a482bbecea5d2ed3f47bf', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
