# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180701_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/6aaaea60b424472f9fd561acacf8e7f4'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/6aaaea60b424472f9fd561acacf8e7f4', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='0d4aaf45b93c45ba8f905ef78b4c7cf5', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
