# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180701_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/f71810acff3b4f73aaebdcc9de2ee93a'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/f71810acff3b4f73aaebdcc9de2ee93a', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='ba0c324359e749b5abc24122f6c0677b', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
