# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180702_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/01ced3313bf541239fa137893283d365'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/01ced3313bf541239fa137893283d365', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='9b4241027d6b425298b4b5b846d26aab', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
