# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180703_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/ac1a1ea37739483fa88e1d8c56e572d4'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/ac1a1ea37739483fa88e1d8c56e572d4', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='55d89854e975437e952df1ee99f30fe3', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
