# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180703_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/716609e1140e486db05ee2558e2b6e0a'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/716609e1140e486db05ee2558e2b6e0a', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='8466ad8c0a2b46a694dc6e440c2005d2', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
