# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180704_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/d7512d8ff23041f7bc80130634258270'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/d7512d8ff23041f7bc80130634258270', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='1c6293f4a10242f1ad033663d2a73d5d', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
