# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180704_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/c3909f72dc334cf2ba24ea70d81bf7de'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/c3909f72dc334cf2ba24ea70d81bf7de', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='750e523aae5d4536b750763050a850b5', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
