# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180706_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/8adc418b76234bd7a5c87ef4cd495050'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/8adc418b76234bd7a5c87ef4cd495050', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='8c24c01a9b50462e980c02993cf7d79d', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
