# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180707_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/1e674ad68f804af6b82e2fc2c10897e9'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/1e674ad68f804af6b82e2fc2c10897e9', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='0d12d7d62c594d3682264e77ccfff294', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
