# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180707_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/9d17eb1f80ab4ce992488afee330f649'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/9d17eb1f80ab4ce992488afee330f649', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('2', '女'), ('1', '男')], default='1', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thesignature',
            field=models.TextField(default='世界为你转身，因为你肯冒险！', max_length=200, verbose_name='用户签名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='27652c693f9e413c84b6f8c7e9ac198d', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
