# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180708_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/16705b9e7fc04833b96f945899751d80'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/16705b9e7fc04833b96f945899751d80', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='a8ea51b45e104d3cb213ca448cd8d135', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
