# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180708_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/f8ea0083eb0f42daaee1c3f0ca451c4c'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/f8ea0083eb0f42daaee1c3f0ca451c4c', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='5379935bd14d42489bccc0b61cc4845c', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
