# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180709_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/da4cc7125015442b94501a1e1bfe3ca0'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/da4cc7125015442b94501a1e1bfe3ca0', verbose_name='背景图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_bh',
            field=models.CharField(default='0c1e6b868c5b4798b19a44db7551538d', max_length=50, unique=True, verbose_name='用户唯一ID'),
        ),
    ]
