# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(max_length=10, verbose_name='系统用户名称')),
                ('sysIntroduction', models.TextField(verbose_name='系统用户简介')),
                ('images', models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/6e1b9c0f1b8747ca93af4f99d8d42bb9', verbose_name='系统用户头像')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系统用户设置',
                'verbose_name_plural': '系统用户设置',
            },
        ),
        migrations.CreateModel(
            name='SysUserthemenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themenu_name', models.CharField(max_length=10, verbose_name='菜单名称')),
                ('urls', models.CharField(max_length=255, verbose_name='小程序跳转路径')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sysuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagess.SysUserModel', verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '系统用户菜单',
                'verbose_name_plural': '系统用户菜单',
            },
        ),
    ]
