# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/359fa695f8d840dfad85dbf9a99209e6', verbose_name='系统用户头像'),
        ),
        migrations.AlterField(
            model_name='sysuserthemenumodel',
            name='sysuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sysusers', to='messagess.SysUserModel', verbose_name='系统用户'),
        ),
    ]
