# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0002_auto_20180709_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysusermodel',
            name='types',
            field=models.CharField(choices=[('0', '消息通知')], default='0', max_length=1, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='sysusermodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SysUserModel/%Y/%m/9c9da1ffa01a4c0188a34e7c021dca50', verbose_name='系统用户头像'),
        ),
    ]
