# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharingSetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_path', models.CharField(choices=[(2, '发现页面'), (4, '内容页面'), (0, '活动页面'), (1, '发布页面'), (3, '消息页面')], default=0, max_length=1, verbose_name='分享页面设置')),
                ('title', models.CharField(max_length=50, verbose_name='分享文字')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/9fc53aa0c421425f85321e194d629daf', verbose_name='分享图片')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '分享页面设置',
                'verbose_name_plural': '分享页面设置',
            },
        ),
    ]
