# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingSet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/3e51ce5723c14b8a89a4bcece4656c3d', verbose_name='分享图片'),
        ),
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='set_path',
            field=models.CharField(choices=[(2, '发现页面'), (3, '消息页面'), (0, '活动页面'), (4, '内容页面'), (1, '发布页面')], default=0, max_length=1, verbose_name='分享页面设置'),
        ),
    ]
