# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingSet', '0017_auto_20180709_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='SharingSet/%y/%d/3dc2ebc2fc4347688f2a68fbc32bfc57', verbose_name='分享图片'),
        ),
        migrations.AlterField(
            model_name='sharingsetmodel',
            name='set_path',
            field=models.CharField(choices=[('1', '活动页面'), ('0', '通用页面'), ('4', '消息页面'), ('3', '发现页面'), ('5', '内容页面'), ('2', '发布页面')], default='0', max_length=1, verbose_name='分享页面设置'),
        ),
    ]
