# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 00:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/68725fe16db64938a3ae2b3275ad64a0', verbose_name='活动图片')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '活动图片管理',
                'verbose_name_plural': '活动图片管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/68725fe16db64938a3ae2b3275ad64a0', verbose_name='封面图片')),
                ('title', models.CharField(max_length=50, verbose_name='活动标题')),
                ('content', models.TextField(max_length=500, verbose_name='活动内容')),
                ('startdate', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('enddate', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间')),
                ('address', models.CharField(max_length=255, verbose_name='活动地点')),
                ('limitnum', models.IntegerField(default=10, verbose_name='限制人数')),
                ('username', models.CharField(max_length=3, verbose_name='真实姓名')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信号')),
                ('groupcode', models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/68725fe16db64938a3ae2b3275ad64a0', verbose_name='群二维码')),
                ('istrue', models.BooleanField(default=False, verbose_name='是否同意协议')),
                ('thedraft', models.BooleanField(default=False, verbose_name='是否发布')),
            ],
            options={
                'verbose_name': '发布活动管理',
                'verbose_name_plural': '发布活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('Introduction', models.TextField(max_length=300, verbose_name='类别简介')),
                ('indexnum', models.IntegerField(default=0, verbose_name='排列顺序')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动类别管理',
                'verbose_name_plural': '活动类别管理',
            },
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='activitytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityTypeModel', verbose_name='活动类别'),
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='activityimagesmodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动'),
        ),
    ]
