# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20180701_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymodel',
            name='latitude',
            field=models.CharField(default=1, max_length=200, verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='longitude',
            field=models.CharField(default=1, max_length=200, verbose_name='经度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/4b20b0906958441fb909978b1e7ad4af', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/4b20b0906958441fb909978b1e7ad4af', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/4b20b0906958441fb909978b1e7ad4af', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/4b20b0906958441fb909978b1e7ad4af', verbose_name='类别图片'),
        ),
    ]
