# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20180701_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=3, verbose_name='真实姓名')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信号')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='报名时间')),
            ],
            options={
                'verbose_name': '活动报名记录',
                'verbose_name_plural': '活动报名记录',
            },
        ),
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/53d12732bc004b0789b1874558591f2d', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/53d12732bc004b0789b1874558591f2d', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/53d12732bc004b0789b1874558591f2d', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/53d12732bc004b0789b1874558591f2d', verbose_name='类别图片'),
        ),
        migrations.AddField(
            model_name='activityuserinfo',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动'),
        ),
    ]
