# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20180701_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityuserinfo',
            name='activity',
        ),
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/cc3a08a189ad47e4843723a2bc971336', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/cc3a08a189ad47e4843723a2bc971336', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/cc3a08a189ad47e4843723a2bc971336', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/cc3a08a189ad47e4843723a2bc971336', verbose_name='类别图片'),
        ),
        migrations.DeleteModel(
            name='ActivityUserInfo',
        ),
    ]
