# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20180702_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimagesmodel',
            name='indexnum',
            field=models.IntegerField(default=0, verbose_name='图片顺序'),
        ),
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/35629ac5ae2f4611ae34be7d2e9740ad', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/35629ac5ae2f4611ae34be7d2e9740ad', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/35629ac5ae2f4611ae34be7d2e9740ad', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/35629ac5ae2f4611ae34be7d2e9740ad', verbose_name='类别图片'),
        ),
    ]
