# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20180702_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='SlideModels/%y/%d/04990b20ae7d454f92d116dfb04e63ab', verbose_name='幻灯片图片')),
                ('indexnum', models.IntegerField(default=0, verbose_name='幻灯片顺序')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '幻灯片管理',
                'verbose_name_plural': '幻灯片管理',
            },
        ),
        migrations.AlterField(
            model_name='activityimagesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityImagesModel/%y/%d/04990b20ae7d454f92d116dfb04e63ab', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/%y/%d/04990b20ae7d454f92d116dfb04e63ab', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='groupcode',
            field=models.ImageField(blank=True, null=True, upload_to='Activity/qr/%y/%d/04990b20ae7d454f92d116dfb04e63ab', verbose_name='群二维码'),
        ),
        migrations.AlterField(
            model_name='activitytypemodel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='ActivityTypeModel/%y/%d/04990b20ae7d454f92d116dfb04e63ab', verbose_name='类别图片'),
        ),
        migrations.AddField(
            model_name='slidemodels',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动'),
        ),
    ]
