# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-01 19:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0006_auto_20180701_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=3, verbose_name='真实姓名')),
                ('wechat', models.CharField(max_length=20, verbose_name='微信号')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='报名时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '活动报名记录',
                'verbose_name_plural': '活动报名记录',
            },
        ),
    ]
