# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 23:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20180703_2335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userOperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='举报时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='举报活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='举报用户')),
            ],
            options={
                'verbose_name': '用户举报记录',
                'verbose_name_plural': '用户举报记录',
            },
        ),
        migrations.CreateModel(
            name='SharingUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='分享时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分享用户')),
            ],
            options={
                'verbose_name': '用户分享记录',
                'verbose_name_plural': '用户分享记录',
            },
        ),
    ]
