# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 23:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20180703_2338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userOperation', '0002_collectionusermodel_sharingusermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporttionUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='举报时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='举报活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='举报用户')),
            ],
            options={
                'verbose_name': '用户举报记录',
                'verbose_name_plural': '用户举报记录',
            },
        ),
        migrations.AlterModelOptions(
            name='collectionusermodel',
            options={'verbose_name': '用户收藏记录', 'verbose_name_plural': '用户收藏记录'},
        ),
        migrations.AlterField(
            model_name='collectionusermodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='收藏活动'),
        ),
        migrations.AlterField(
            model_name='collectionusermodel',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='collectionusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收藏用户'),
        ),
    ]
