# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0003_auto_20180703_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttionusermodel',
            name='contion',
            field=models.TextField(default=1, verbose_name='举报理由'),
            preserve_default=False,
        ),
    ]
