# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0005_browseusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityuserinfo',
            name='type',
            field=models.CharField(choices=[('1', '活动参加人'), ('0', '活动发起人')], default='1', max_length=1, verbose_name='报名用户类型'),
        ),
    ]
