# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 17:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_auto_20180707_1720'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userOperation', '0006_activityuserinfo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centent', models.TextField(max_length=300, verbose_name='评论内容')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityModel', verbose_name='评论活动')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='userOperation.CommentsModels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
            },
        ),
        migrations.AlterField(
            model_name='activityuserinfo',
            name='type',
            field=models.CharField(choices=[('0', '活动发起人'), ('1', '活动参加人')], default='1', max_length=1, verbose_name='报名用户类型'),
        ),
    ]
