# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0007_auto_20180707_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodels',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='userOperation.CommentsModels', verbose_name='父评论'),
        ),
    ]
