# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userOperation', '0009_auto_20180708_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityuserinfo',
            name='type',
            field=models.CharField(choices=[('1', '活动参加人'), ('0', '活动发起人')], default='1', max_length=1, verbose_name='报名用户类型'),
        ),
        migrations.AlterField(
            model_name='collectionusermodel',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_dbs', to='activity.ActivityModel', verbose_name='收藏活动'),
        ),
    ]
