# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 11:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userOperation', '0010_auto_20180708_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='反馈标题')),
                ('centent', models.TextField(max_length=300, verbose_name='反馈内容')),
                ('images', models.ImageField(blank=True, null=True, upload_to='FeedBackModels/%y/%d/2c8f8332ed8247cda2711cae0bfb0ebb', verbose_name='分享图片')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='反馈时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
            ],
            options={
                'verbose_name': '用户反馈记录',
                'verbose_name_plural': '用户反馈记录',
            },
        ),
        migrations.AlterModelOptions(
            name='commentsmodels',
            options={'verbose_name': '用户评论记录', 'verbose_name_plural': '用户评论'},
        ),
    ]
